name: Deploy on servers
on:
  workflow_run:
    workflows: ["npm-publish"]
    types:
      - completed
  workflow_dispatch:
jobs:
  fr-1:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: s3.fr-1.jeyserver.com
          username: root
          privateKey: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY}}
          command: |
            npm install -g @dnj/minio-gateway@${{ env.GITHUB_REF_NAME }}
            service minio-gateway restart
    environment:
      name: s3.fr-1.jeyserver.com
      url: https://s3.fr-1.jeyserver.com


  de-1:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: s3.de-1.jeyserver.com
          username: root
          privateKey: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY}}
          command: |
            npm install -g @dnj/minio-gateway@${{ env.GITHUB_REF_NAME }}
            service minio-gateway restart
    environment:
      name: s3.de-1.jeyserver.com
      url: https://s3.de-1.jeyserver.com